---
apiVersion: v1
kind: Namespace
metadata: 
  name: myns
  labels: 
    dept: engineering
    app: fortune
---
apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod
  namespace: myns
  labels:
    dept: engineering
    app: fortune
spec:
  containers:
  - name: fortune-container
    image: tanwk3/myapp:v1
    imagePullPolicy: IfNotPresent
    env:
      - name: APP_PORT
        value: "8080"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: fortune-port
        containerPort: 8080
